package pojos;
// Generated Aug 7, 2022 5:00:05 PM by Hibernate Tools 4.3.1



/**
 * Complaint generated by hbm2java
 */
public class Complaint  implements java.io.Serializable {


     private Integer id;
     private String comp;
     private String createdAt;

    public Complaint() {
    }

    public Complaint(String comp, String createdAt) {
       this.comp = comp;
       this.createdAt = createdAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getComp() {
        return this.comp;
    }
    
    public void setComp(String comp) {
        this.comp = comp;
    }
    public String getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }




}


